{% set name = "gemgis" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/GemGIS-{{ version }}.tar.gz
  sha256: 19b99d26ea1ef4ddcc7c2dab9d266673095dabde1a8943614937ad1116911f98

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=68.1.2
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - geopandas
    - rasterio
    - pyvista

test:
  imports:
    - gemgis
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cgre-aachen/gemgis
  license: LGPL-3.0-only
  license_family: LGPL
  license_file: LICENSE
  summary: GemGIS is a Python-based, open-source spatial data processing library. It is capable of preprocessing spatial data such as vector data raster data, data obtained from online services and many more data formats. GemGIS wraps and extends the functionality of packages known to the geo-community such as GeoPandas,
    Rasterio, OWSLib, Shapely, PyVista, Pandas, and NumPy.
  doc_url: https://gemgis.readthedocs.io/en/latest
  dev_url: https://github.com/cgre-aachen/gemgis

extra:
  recipe-maintainers:
    - AlexanderJuestel
